# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LoadBalancer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12LoadBalancer.proto\x1a\x1bgoogle/protobuf/empty.proto\"&\n\rServerAddress\x12\x15\n\rserveraddress\x18\x01 \x01(\t\"/\n\x0cLoadBalancer\x12\x1f\n\x07servers\x18\x01 \x03(\x0b\x32\x0e.ServerAddress2O\n\x13LoadBalancerService\x12\x38\n\x0c\x43hooseServer\x12\x16.google.protobuf.Empty\x1a\x0e.ServerAddress\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LoadBalancer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVERADDRESS._serialized_start=51
  _SERVERADDRESS._serialized_end=89
  _LOADBALANCER._serialized_start=91
  _LOADBALANCER._serialized_end=138
  _LOADBALANCERSERVICE._serialized_start=140
  _LOADBALANCERSERVICE._serialized_end=219
# @@protoc_insertion_point(module_scope)
