# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10SensorData.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"w\n\x0cRawMeteoData\x12\x11\n\tsensor_id\x18\x01 \x01(\x05\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x10\n\x08humidity\x18\x03 \x01(\x02\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"a\n\x10RawPollutionData\x12\x11\n\tsensor_id\x18\x01 \x01(\x05\x12\x0b\n\x03\x63o2\x18\x02 \x01(\x05\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"-\n\x16\x41irWellnessCoefficient\x12\x13\n\x0b\x61irwellness\x18\x01 \x01(\x02\")\n\x14PollutionCoefficient\x12\x11\n\tpollution\x18\x01 \x01(\x02\"\"\n\rSensorRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\t\"s\n\x0eSensorResponse\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08humidity\x18\x02 \x01(\x02\x12\x0b\n\x03\x63o2\x18\x03 \x01(\x05\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xc5\x02\n\x11SensorDataService\x12\x32\n\rGetSensorData\x12\x0e.SensorRequest\x1a\x0f.SensorResponse\"\x00\x12\x38\n\rSendMeteoData\x12\r.RawMeteoData\x1a\x16.google.protobuf.Empty\"\x00\x12@\n\x11SendPollutionData\x12\x11.RawPollutionData\x1a\x16.google.protobuf.Empty\"\x00\x12<\n\x10ProcessMeteoData\x12\r.RawMeteoData\x1a\x17.AirWellnessCoefficient\"\x00\x12\x42\n\x14ProcessPollutionData\x12\x11.RawPollutionData\x1a\x15.PollutionCoefficient\"\x00\x32\xd4\x02\n\x12ProxyReturnService\x12N\n\x19GetAirwellnessCoefficient\x12\x16.google.protobuf.Empty\x1a\x17.AirWellnessCoefficient\"\x00\x12M\n\x1aGetAirPollutionCoefficient\x12\x16.google.protobuf.Empty\x1a\x15.PollutionCoefficient\"\x00\x12O\n\x1aSendAirWellnessCoefficient\x12\x17.AirWellnessCoefficient\x1a\x16.google.protobuf.Empty\"\x00\x12N\n\x1bSendAirPollutionCoefficient\x12\x15.PollutionCoefficient\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SensorData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RAWMETEODATA._serialized_start=82
  _RAWMETEODATA._serialized_end=201
  _RAWPOLLUTIONDATA._serialized_start=203
  _RAWPOLLUTIONDATA._serialized_end=300
  _AIRWELLNESSCOEFFICIENT._serialized_start=302
  _AIRWELLNESSCOEFFICIENT._serialized_end=347
  _POLLUTIONCOEFFICIENT._serialized_start=349
  _POLLUTIONCOEFFICIENT._serialized_end=390
  _SENSORREQUEST._serialized_start=392
  _SENSORREQUEST._serialized_end=426
  _SENSORRESPONSE._serialized_start=428
  _SENSORRESPONSE._serialized_end=543
  _SENSORDATASERVICE._serialized_start=546
  _SENSORDATASERVICE._serialized_end=871
  _PROXYRETURNSERVICE._serialized_start=874
  _PROXYRETURNSERVICE._serialized_end=1214
# @@protoc_insertion_point(module_scope)
